# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 字节君
subtitle: 热爱漫无边际，生活自有分寸
avatar: https://cdn.staticaly.com/gh/Bytelv/lvbyteCdn@main/20230104/%E8%8B%B9%E6%9E%9C.156l7bksen40.jpg
favicon: https://cdn.staticaly.com/gh/Bytelv/lvbyteCdn@main/20230104/%E8%8B%B9%E6%9E%9C.156l7bksen40.jpg
description: 漂泊在浩瀚宇宙的小行星
keywords: 初中,极客,编程,计算机
author: lvbyte
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.lvbyte.top
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar








# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repo: https://github.com:Bytelv/Myblog.git # 注意要把地址改为自己的仓库地址
    branch: main
    message: "Build at {{ now('YYYY-MM-DD HH:mm:ss Z') }}"
  - type: cjh_bing_url_submitter
  - type: cjh_baidu_url_submitter
inject:
  head:
    - <link rel="preconnect" href="https://s1.hdslb.com/" />

    - <meta name="baidu-site-verification" content="codeva-PolTe1ZwAJ" /> #blog.lvbyte.top百度验证
    - <link rel="stylesheet" href="/Code.css">
  script:
    - <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
   # - <script src="https://cdn.jsdelivr.net/gh/fz6m/china-lantern@1.6/dist/china-lantern.min.js"></script> #中国春节红灯笼
  #  - <script src="https://unpkg.com/magic-snowflakes/dist/snowflakes.min.js"></script> #引入雪花
  #  - <script> var sf = new Snowflakes(); </script> #开启雪花
    - <script> loadStatistic("https://qexo.lvbyte.top") </script> #引入QEXO统计JS
   # - <script src="https://recaptcha.net/recaptcha/api.js?render=_reCAPTCHA_site_key"></script>
  #  - <script>grecaptcha.ready(function(){grecaptcha.execute('6Ldd7hgkAAAAADn8MJoUaZ0z0JLRjRqPyrQ-Gb5Y',{action:'homepage'}).then(function(token){console.log(token)})});</script>
    - <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/bytelv/lvbyteCdn@main/Code.js"></script>

  footer:
    - <span id="busuanzi_container_site_pv">本站总访问量<span id="busuanzi_value_site_pv"></span>次</span>
    - 站点访问量 <span id="qexo-site-pv">Loading...</span>
    - 站点访客数 <span id="qexo-site-uv">Loading...</span>
    - 页面访问量 <span id="qexo-page-pv">Loading...</span>
    - <script src="https://cdn.jsdelivr.net/npm/qexo-static@1.3.0/hexo/statistic/statistic.min.js"></script>


sitemap:
 path: sitemap.xml
baidusitemap:
 path: baidusitemap.xml
 


 
# Extensions
## Plugins: http://hexo.io/plugins/
#RSS订阅
plugin:
- hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20 





